### ISSUE TITLE
Unable to find resourceId in '$file' file name, when running as pipeline

### ISSUE THREAD

**Issue by maudlinp** [ztrhgf/DevOps_Pipelines#4]
We have been running IntuneCD via DevOps pipeline successfully for many months. Followed the steps on https://doitpsway.com/how-to-easily-backup-your-intune-environment-using-intunecd-and-azure-devops-pipeline. On 2/13/2024, at 7:00 PM CST, the pipeline failed. It first failed at step "Create Intune Backup" and specified that the application needed to be granted DeviceManagementRBAC.Read.All rights. This was completed and the pipeline moved on past that step. Now at the step called "Find Change Author & Commit The Backup", it fails with the following error.

Exception: /home/vsts/work/_temp/163166ea-6cc7-4511-acd5-865f3d79e280.ps1:227
Line |
227 | throw "Unable to find resourceId in '$file' file name. Pipe …
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Unable to find resourceId in 'prod-backup/Scope Tags/Default__0.json'
| file name. Pipeline code modification needed, because some changes in
| IntuneCD were made probably.

##[error]PowerShell exited with code '1'.

To Reproduce
Steps to reproduce the behavior: Run the pipeline described in https://doitpsway.com/how-to-easily-backup-your-intune-environment-using-intunecd-and-azure-devops-pipeline

It looks like a few files were updated on 2/13 and 2/14, and they may be the root cause. Thanks for looking into it.

Expected behavior
The expectation is that that step in the pipeline can complete successfully and move on in job.

Screenshots

Run type (please complete the following information):

Mode: [e.g. 0 or 1]
Client [e.g. Pipeline, local machine] Pipeline
Version [e.g. 1.0.2] Setup.cfg says that it was updated 8 hours ago to 2.1.1

**Comment by maudlinp** [comment]
I am no developer but it looks like the only line of code changed recently was line 64? Perhaps it is a space necessary before the \ at the end?
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/160069995/6d33e73c-0e54-45c7-8bd8-f48fd0246de2)

**Comment by maudlinp** [comment]
I suspect that something changed in IntuneCD that doesn't work with your YAML code now?

**Comment by ztrhgf** [comment]
Yep, the problem is that the new IntuneCD version [2.1.0](https://github.com/almenscorner/IntuneCD/releases/tag/v2.1.0) backups additional Intune data.
I need to update my pipeline.

For now you have to [exclude ScopeTag backup](https://github.com/almenscorner/IntuneCD/wiki/Backup#arguments) via altering "--exclude ScopeTags"

**Comment by ztrhgf** [comment]
OK so this is strange.

For me this is working perfectly fine. are you absolutely sure your pipeline is not edited in any way?

The problem here is probably the thing that **resourceId** of default scope tag is **zero**. Which probably causes trouble in pipeline line 266
```
if ($resourceId) {
```

But it shouldn't because internal function _getResourceId returns it as a string which should be treated as true when if condition is calculated.

So please try to modify pipeline line 266 to
```
if ([string]::IsNullOrEmpty($resourceId)) {
```

**Comment by maudlinp** [comment]
Thanks for the responses! My apologies for not getting back sooner, I was out of the office.

I took the updated code you have and just replaced the variables at the top. It is now working again without error. I didn't need to edit the script beyond the personal variables at the top.

Thanks again for all of your help! This script is the best thing since sliced bread. It is so helpful to see what changes have been made on a daily basis.
