### ISSUE TITLE
Failing at Create Intune Backup- unrecognized arguments: -t ***

### ISSUE THREAD

**Issue by dernerl** [ztrhgf/DevOps_Pipelines#9]
Hello, I'm getting following error.
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/50828248/b8a738e8-6c4f-43a9-b2e9-3ee665a781c4)

Do you have any idea what could be causing this?

**Comment by ztrhgf** [comment]
The error says it all I think. 
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/2930419/c96442f4-4db3-4819-af4c-b35dd449fd77)

Try to modify the pipeline code to use `--token` instead of `-t` and let me know if that helps.

https://github.com/almenscorner/IntuneCD/wiki/Backup

**Comment by dernerl** [comment]
Thanks for your quick reply. Unfortunately it didn't work that way either
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/50828248/b0b676e7-6c86-423b-8e2a-7ba8ef542945)

for me, the token looks good, but is there an error?
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/50828248/5b8842b4-2fa2-4c80-9e63-9e1991037c52)

**Comment by ztrhgf** [comment]
Was this pipeline working and then suddenly stopped or was never working for you?

It might be the problem with used AZ modules. I know some version are buggy, so maybe try to use older/newer ones. Also I would output the received token to the pipeline so you can see that it is a valid string. Because it seems like the variable that should contain the token is empty or invalid in some way. Therefore the syntax error.

**Comment by dernerl** [comment]
okay, I'll try to get to grips with it.
These are my first steps in Azure DevOps and so far I've only followed your instructions (https://doitpshway.com/how-to-easily-backup-your-intune-environment-using-intunecd-and-azure-devops-pipeline).

But I'll let you know when I've found something! :-)

**Comment by ztrhgf** [comment]
OK.

For me, it is working so its probably some moving part like module version, etc.

**Comment by dernerl** [comment]
>  moving part like module version, IntuneCD version, etc.

sorry for this beginner question, but how can I change such variables in the environment? How do I influence this? Have u any ressource, where I can read more about it?

**Comment by ztrhgf** [comment]
OK.

How to output the token to validate this part is working:
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/2930419/2587586a-d639-4c50-abd4-730c1a3b6f72)

How to output that the token got the IntuneCD job
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/2930419/0237491d-ad3d-4bec-9ec2-2ee03c2b3878)

How to change what IntuneCD version should be used:
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/2930419/a54b213a-4c3c-4559-a183-d1a574358b96)

**Comment by dernerl** [comment]
Thanks for ur input!
The token looks good
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/50828248/bf22b8c5-0664-4f71-bb0e-07f3a9cb1178)
in the section "Create Intune backup" I see the token output as a secret *** which should also good.
Your last tip with "Install IntuneCD" I'm getting an error with "==2.3.1" doesn't found this version
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/50828248/5e6a3127-4691-4461-bb7a-dd590bf79b1d)
`ERROR: Could not find a version that satisfies the requirement IntuneCD==2.3.1 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.4.0b1, 1.4.0b2, 1.4.0, 1.4.1b1, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5b1, 1.4.5b2, 1.4.5, 1.4.6b1, 1.4.6, 1.4.7b1, 1.4.7, 1.4.8b1, 1.4.8, 1.4.9, 1.5.0, 1.5.1, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0b5, 2.0.0, 2.0.1, 2.0.2b1, 2.0.2, 2.0.3b1, 2.0.3b2, 2.0.3, 2.0.4b1, 2.0.4b2, 2.0.4b3, 2.0.4, 2.0.5b1, 2.0.5b2, 2.0.5, 2.0.6, 2.0.7, 2.0.8b1, 2.0.8, 2.0.9b1, 2.0.9b2, 2.0.9b3, 2.0.9b4, 2.1.0b1, 2.1.0, 2.1.1, 2.1.2b1, 2.1.2b2, 2.1.2b3, 2.1.2, 2.2.0b1, 2.2.0b2, 2.2.0b3, 2.2.0b4, 2.2.0b5, 2.2.0b6, 2.2.0b7, 2.2.0, 2.3.0b1, 2.3.0b2, 2.3.0b3, 2.3.0b4, 2.3.0b5, 2.3.0b6, 2.3.0b7, 2.3.0b8, 2.3.0rc1, 2.3.0rc2)`
But this has looked me at the previous runs and i found this:
Does the normal call, only install version 2.2.0?
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/50828248/7790f658-ab9a-44a6-8a5d-3b3aeead951d)
that would explain why the token cannot be found, since it was only developed with version 2.3.0

**Comment by dernerl** [comment]
I altered the code to the last version shown in the error message 
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/50828248/8108ffec-1bdc-45b9-9097-c17135bf8706)
Which installs IntuneCD but lead me to an other error
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/50828248/f071b76c-8325-4fe4-9200-51fa6d3cef7a)
Is this a new issue?
But 2.3.0 is not the latest version. 2.3.3 cannot be installed either.
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/50828248/fe094dd0-373c-40de-ac84-2a17362c48ba)
Is this an issue at IntuneCD or have you another idea? 
is 2.3.3 installed on your instance and if so, why is it not installed on your computer and not on mine? :-)

ps: I'm new to the devops world, especially github and obviously also azure devops and pipelines, I'm a classic system administrator. If I'm doing something wrong, please feel free to point it out to me!

pps: Thank you very much for your time, your blog and this troubleshooting have already been very helpful to me! By the way, I successfully got the other blog post about Azure Config to work.

**Comment by ztrhgf** [comment]
My pipeline installs 2.3.3 version, because without specifying the specific version, by default the newest one gets installed. That was the reason I suggested you to try some older one.
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/2930419/f10759c3-5281-40e5-b015-08356f3b89e0)
and the pipeline code looks like this 
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/2930419/6a0441fa-01a3-4e27-8a6d-3b1597adde77)

I am a sys admin too, but it's not enough in today's IT unfortunately :D But I am glad that Azure backup works for you!

IntuneCD errors like you sent are outside my expertise and should be solved by the IntuneCD author by creating a new [issue](https://github.com/almenscorner/IntuneCD/issues).

Anyway I am a little bit out of ideas right now. What you can try is to install the IntuneCD locally and pass the token (retrieved from the pipeline run) directly to it, if the error will be the same. And maybe even this particular issue you could try to solve with the author himself.

**Comment by dernerl** [comment]
A Workaround mentioned in https://github.com/almenscorner/IntuneCD/issues/191#issuecomment-2039227955 resolve my problem.
With ubuntu-latest an old version of IntuneCD is being installed
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/50828248/88ae6301-cea8-402d-b55e-3b12c1b3e883)
with ubuntu-22.04 the latest version of IntuneCD is being installed
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/50828248/930e11b4-7a98-4d7c-afd1-3cc75a15a8d3)

@ztrhgf Thanks again for your support!
